-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.CommentAuthor exposing (email, id, name, url)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| The email for the comment author
-}
email : SelectionSet (Maybe String) Wordpress.Object.CommentAuthor
email =
    Object.selectionForField "(Maybe String)" "email" [] (Decode.string |> Decode.nullable)


{-| The globally unique identifier for the Comment Author user
-}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.CommentAuthor
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The name for the comment author.
-}
name : SelectionSet (Maybe String) Wordpress.Object.CommentAuthor
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The url the comment author.
-}
url : SelectionSet (Maybe String) Wordpress.Object.CommentAuthor
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
