-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.DeleteUserPayload exposing (clientMutationId, deletedId, user)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| -}
clientMutationId : SelectionSet String Wordpress.Object.DeleteUserPayload
clientMutationId =
    Object.selectionForField "String" "clientMutationId" [] Decode.string


{-| The ID of the user that you just deleted
-}
deletedId : SelectionSet (Maybe Wordpress.ScalarCodecs.Id) Wordpress.Object.DeleteUserPayload
deletedId =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "deletedId" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)


{-| The deleted user object
-}
user : SelectionSet decodesTo Wordpress.Object.User -> SelectionSet (Maybe decodesTo) Wordpress.Object.DeleteUserPayload
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)
