-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.LoginPayload exposing (authToken, clientMutationId, refreshToken, user)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| JWT Token that can be used in future requests for Authentication
-}
authToken : SelectionSet (Maybe String) Wordpress.Object.LoginPayload
authToken =
    Object.selectionForField "(Maybe String)" "authToken" [] (Decode.string |> Decode.nullable)


{-| A JWT token that can be used in future requests to get a refreshed jwtAuthToken. If the refresh token used in a request is revoked or otherwise invalid, a valid Auth token will NOT be issued in the response headers.
-}
refreshToken : SelectionSet (Maybe String) Wordpress.Object.LoginPayload
refreshToken =
    Object.selectionForField "(Maybe String)" "refreshToken" [] (Decode.string |> Decode.nullable)


{-| The user that was logged in
-}
user : SelectionSet decodesTo Wordpress.Object.User -> SelectionSet (Maybe decodesTo) Wordpress.Object.LoginPayload
user object_ =
    Object.selectionForCompositeField "user" [] object_ (identity >> Decode.nullable)


{-| -}
clientMutationId : SelectionSet String Wordpress.Object.LoginPayload
clientMutationId =
    Object.selectionForField "String" "clientMutationId" [] Decode.string
