-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.MediaSize exposing (file, height, mimeType, name, sourceUrl, width)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| The file of the for the referenced size
-}
file : SelectionSet (Maybe String) Wordpress.Object.MediaSize
file =
    Object.selectionForField "(Maybe String)" "file" [] (Decode.string |> Decode.nullable)


{-| The height of the for the referenced size
-}
height : SelectionSet (Maybe String) Wordpress.Object.MediaSize
height =
    Object.selectionForField "(Maybe String)" "height" [] (Decode.string |> Decode.nullable)


{-| The mime type of the resource
-}
mimeType : SelectionSet (Maybe String) Wordpress.Object.MediaSize
mimeType =
    Object.selectionForField "(Maybe String)" "mimeType" [] (Decode.string |> Decode.nullable)


{-| The referenced size name
-}
name : SelectionSet (Maybe String) Wordpress.Object.MediaSize
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The url of the for the referenced size
-}
sourceUrl : SelectionSet (Maybe String) Wordpress.Object.MediaSize
sourceUrl =
    Object.selectionForField "(Maybe String)" "sourceUrl" [] (Decode.string |> Decode.nullable)


{-| The width of the for the referenced size
-}
width : SelectionSet (Maybe String) Wordpress.Object.MediaSize
width =
    Object.selectionForField "(Maybe String)" "width" [] (Decode.string |> Decode.nullable)
