-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.MediaItemMeta exposing (aperture, camera, caption, copyright, createdTimestamp, credit, focalLength, iso, keywords, orientation, shutterSpeed, title)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| -}
aperture : SelectionSet (Maybe Float) Wordpress.Object.MediaItemMeta
aperture =
    Object.selectionForField "(Maybe Float)" "aperture" [] (Decode.float |> Decode.nullable)


{-| -}
camera : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
camera =
    Object.selectionForField "(Maybe String)" "camera" [] (Decode.string |> Decode.nullable)


{-| -}
caption : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
caption =
    Object.selectionForField "(Maybe String)" "caption" [] (Decode.string |> Decode.nullable)


{-| -}
copyright : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
copyright =
    Object.selectionForField "(Maybe String)" "copyright" [] (Decode.string |> Decode.nullable)


{-| -}
createdTimestamp : SelectionSet (Maybe Int) Wordpress.Object.MediaItemMeta
createdTimestamp =
    Object.selectionForField "(Maybe Int)" "createdTimestamp" [] (Decode.int |> Decode.nullable)


{-| -}
credit : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
credit =
    Object.selectionForField "(Maybe String)" "credit" [] (Decode.string |> Decode.nullable)


{-| -}
focalLength : SelectionSet (Maybe Int) Wordpress.Object.MediaItemMeta
focalLength =
    Object.selectionForField "(Maybe Int)" "focalLength" [] (Decode.int |> Decode.nullable)


{-| -}
iso : SelectionSet (Maybe Int) Wordpress.Object.MediaItemMeta
iso =
    Object.selectionForField "(Maybe Int)" "iso" [] (Decode.int |> Decode.nullable)


{-| -}
keywords : SelectionSet (Maybe (List (Maybe String))) Wordpress.Object.MediaItemMeta
keywords =
    Object.selectionForField "(Maybe (List (Maybe String)))" "keywords" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| -}
orientation : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
orientation =
    Object.selectionForField "(Maybe String)" "orientation" [] (Decode.string |> Decode.nullable)


{-| -}
shutterSpeed : SelectionSet (Maybe Float) Wordpress.Object.MediaItemMeta
shutterSpeed =
    Object.selectionForField "(Maybe Float)" "shutterSpeed" [] (Decode.float |> Decode.nullable)


{-| -}
title : SelectionSet (Maybe String) Wordpress.Object.MediaItemMeta
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
