-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.MenuItem exposing (ChildItemsOptionalArguments, childItems, connectedObject, cssClasses, description, id, label, linkRelationship, menuItemId, target, title, url)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


type alias ChildItemsOptionalArguments =
    { first : OptionalArgument Int
    , last : OptionalArgument Int
    , after : OptionalArgument String
    , before : OptionalArgument String
    , where_ : OptionalArgument Wordpress.InputObject.MenuItemToMenuItemConnectionWhereArgs
    }


{-| Connection between the MenuItem type and the MenuItem type

  - first - The number of items to return after the referenced "after" cursor
  - after - Cursor used along with the "first" argument to reference where in the dataset to get data
  - before - Cursor used along with the "last" argument to reference where in the dataset to get data
  - where\_ - Arguments for filtering the connection

-}
childItems : (ChildItemsOptionalArguments -> ChildItemsOptionalArguments) -> SelectionSet decodesTo Wordpress.Object.MenuItemToMenuItemConnection -> SelectionSet (Maybe decodesTo) Wordpress.Object.MenuItem
childItems fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { first = Absent, last = Absent, after = Absent, before = Absent, where_ = Absent }

        optionalArgs =
            [ Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "where" filledInOptionals.where_ Wordpress.InputObject.encodeMenuItemToMenuItemConnectionWhereArgs ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "childItems" optionalArgs object_ (identity >> Decode.nullable)


{-| The object connected to this menu item.
-}
connectedObject : SelectionSet decodesTo Wordpress.Union.MenuItemObjectUnion -> SelectionSet (Maybe decodesTo) Wordpress.Object.MenuItem
connectedObject object_ =
    Object.selectionForCompositeField "connectedObject" [] object_ (identity >> Decode.nullable)


{-| Class attribute for the menu item link
-}
cssClasses : SelectionSet (Maybe (List (Maybe String))) Wordpress.Object.MenuItem
cssClasses =
    Object.selectionForField "(Maybe (List (Maybe String)))" "cssClasses" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| Description of the menu item.
-}
description : SelectionSet (Maybe String) Wordpress.Object.MenuItem
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| Relay ID of the menu item.
-}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.MenuItem
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Label or title of the menu item.
-}
label : SelectionSet (Maybe String) Wordpress.Object.MenuItem
label =
    Object.selectionForField "(Maybe String)" "label" [] (Decode.string |> Decode.nullable)


{-| Link relationship (XFN) of the menu item.
-}
linkRelationship : SelectionSet (Maybe String) Wordpress.Object.MenuItem
linkRelationship =
    Object.selectionForField "(Maybe String)" "linkRelationship" [] (Decode.string |> Decode.nullable)


{-| WP ID of the menu item.
-}
menuItemId : SelectionSet (Maybe Int) Wordpress.Object.MenuItem
menuItemId =
    Object.selectionForField "(Maybe Int)" "menuItemId" [] (Decode.int |> Decode.nullable)


{-| Target attribute for the menu item link.
-}
target : SelectionSet (Maybe String) Wordpress.Object.MenuItem
target =
    Object.selectionForField "(Maybe String)" "target" [] (Decode.string |> Decode.nullable)


{-| Title attribute for the menu item link
-}
title : SelectionSet (Maybe String) Wordpress.Object.MenuItem
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)


{-| URL or destination of the menu item.
-}
url : SelectionSet (Maybe String) Wordpress.Object.MenuItem
url =
    Object.selectionForField "(Maybe String)" "url" [] (Decode.string |> Decode.nullable)
