-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.Plugin exposing (author, authorUri, description, id, name, pluginUri, version)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| Name of the plugin author(s), may also be a company name.
-}
author : SelectionSet (Maybe String) Wordpress.Object.Plugin
author =
    Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


{-| URI for the related author(s)/company website.
-}
authorUri : SelectionSet (Maybe String) Wordpress.Object.Plugin
authorUri =
    Object.selectionForField "(Maybe String)" "authorUri" [] (Decode.string |> Decode.nullable)


{-| Description of the plugin.
-}
description : SelectionSet (Maybe String) Wordpress.Object.Plugin
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.Plugin
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Display name of the plugin.
-}
name : SelectionSet (Maybe String) Wordpress.Object.Plugin
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| URI for the plugin website. This is useful for directing users for support requests etc.
-}
pluginUri : SelectionSet (Maybe String) Wordpress.Object.Plugin
pluginUri =
    Object.selectionForField "(Maybe String)" "pluginUri" [] (Decode.string |> Decode.nullable)


{-| Current version of the plugin.
-}
version : SelectionSet (Maybe String) Wordpress.Object.Plugin
version =
    Object.selectionForField "(Maybe String)" "version" [] (Decode.string |> Decode.nullable)
