-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.RefreshJwtAuthTokenPayload exposing (authToken, clientMutationId)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| JWT Token that can be used in future requests for Authentication
-}
authToken : SelectionSet (Maybe String) Wordpress.Object.RefreshJwtAuthTokenPayload
authToken =
    Object.selectionForField "(Maybe String)" "authToken" [] (Decode.string |> Decode.nullable)


{-| -}
clientMutationId : SelectionSet String Wordpress.Object.RefreshJwtAuthTokenPayload
clientMutationId =
    Object.selectionForField "String" "clientMutationId" [] Decode.string
