-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.RestoreCommentPayload exposing (clientMutationId, comment, restoredId)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| -}
clientMutationId : SelectionSet String Wordpress.Object.RestoreCommentPayload
clientMutationId =
    Object.selectionForField "String" "clientMutationId" [] Decode.string


{-| The restored comment object
-}
comment : SelectionSet decodesTo Wordpress.Object.Comment -> SelectionSet (Maybe decodesTo) Wordpress.Object.RestoreCommentPayload
comment object_ =
    Object.selectionForCompositeField "comment" [] object_ (identity >> Decode.nullable)


{-| The ID of the restored comment
-}
restoredId : SelectionSet (Maybe Wordpress.ScalarCodecs.Id) Wordpress.Object.RestoreCommentPayload
restoredId =
    Object.selectionForField "(Maybe ScalarCodecs.Id)" "restoredId" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder |> Decode.nullable)
