-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.Tag exposing (PostsOptionalArguments, count, description, id, link, name, posts, slug, tagId, taxonomy, termGroupId, termTaxonomyId)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| The number of objects connected to the object
-}
count : SelectionSet (Maybe Int) Wordpress.Object.Tag
count =
    Object.selectionForField "(Maybe Int)" "count" [] (Decode.int |> Decode.nullable)


{-| The description of the object
-}
description : SelectionSet (Maybe String) Wordpress.Object.Tag
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| The global ID for the post\_tag
-}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.Tag
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The link to the term
-}
link : SelectionSet (Maybe String) Wordpress.Object.Tag
link =
    Object.selectionForField "(Maybe String)" "link" [] (Decode.string |> Decode.nullable)


{-| The human friendly name of the object.
-}
name : SelectionSet (Maybe String) Wordpress.Object.Tag
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


type alias PostsOptionalArguments =
    { first : OptionalArgument Int
    , last : OptionalArgument Int
    , after : OptionalArgument String
    , before : OptionalArgument String
    , where_ : OptionalArgument Wordpress.InputObject.TagToPostConnectionWhereArgs
    }


{-| Connection between the tag type and the tag type

  - first - The number of items to return after the referenced "after" cursor
  - after - Cursor used along with the "first" argument to reference where in the dataset to get data
  - before - Cursor used along with the "last" argument to reference where in the dataset to get data
  - where\_ - Arguments for filtering the connection

-}
posts : (PostsOptionalArguments -> PostsOptionalArguments) -> SelectionSet decodesTo Wordpress.Object.TagToPostConnection -> SelectionSet (Maybe decodesTo) Wordpress.Object.Tag
posts fillInOptionals object_ =
    let
        filledInOptionals =
            fillInOptionals { first = Absent, last = Absent, after = Absent, before = Absent, where_ = Absent }

        optionalArgs =
            [ Argument.optional "first" filledInOptionals.first Encode.int, Argument.optional "last" filledInOptionals.last Encode.int, Argument.optional "after" filledInOptionals.after Encode.string, Argument.optional "before" filledInOptionals.before Encode.string, Argument.optional "where" filledInOptionals.where_ Wordpress.InputObject.encodeTagToPostConnectionWhereArgs ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "posts" optionalArgs object_ (identity >> Decode.nullable)


{-| An alphanumeric identifier for the object unique to its type.
-}
slug : SelectionSet (Maybe String) Wordpress.Object.Tag
slug =
    Object.selectionForField "(Maybe String)" "slug" [] (Decode.string |> Decode.nullable)


{-| The id field matches the WP\_Post-&gt;ID field.
-}
tagId : SelectionSet (Maybe Int) Wordpress.Object.Tag
tagId =
    Object.selectionForField "(Maybe Int)" "tagId" [] (Decode.int |> Decode.nullable)


{-| The name of the taxonomy this term belongs to
-}
taxonomy : SelectionSet decodesTo Wordpress.Object.Taxonomy -> SelectionSet (Maybe decodesTo) Wordpress.Object.Tag
taxonomy object_ =
    Object.selectionForCompositeField "taxonomy" [] object_ (identity >> Decode.nullable)


{-| The ID of the term group that this term object belongs to
-}
termGroupId : SelectionSet (Maybe Int) Wordpress.Object.Tag
termGroupId =
    Object.selectionForField "(Maybe Int)" "termGroupId" [] (Decode.int |> Decode.nullable)


{-| The taxonomy ID that the object is associated with
-}
termTaxonomyId : SelectionSet (Maybe Int) Wordpress.Object.Tag
termTaxonomyId =
    Object.selectionForField "(Maybe Int)" "termTaxonomyId" [] (Decode.int |> Decode.nullable)
