-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.Theme exposing (author, authorUri, description, id, name, screenshot, slug, tags, themeUri, version)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| Name of the theme author(s), could also be a company name. This field is equivalent to WP\_Theme-&gt;get( &quot;Author&quot; ).
-}
author : SelectionSet (Maybe String) Wordpress.Object.Theme
author =
    Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


{-| URI for the author/company website. This field is equivalent to WP\_Theme-&gt;get( &quot;AuthorURI&quot; ).
-}
authorUri : SelectionSet (Maybe String) Wordpress.Object.Theme
authorUri =
    Object.selectionForField "(Maybe String)" "authorUri" [] (Decode.string |> Decode.nullable)


{-| The description of the theme. This field is equivalent to WP\_Theme-&gt;get( &quot;Description&quot; ).
-}
description : SelectionSet (Maybe String) Wordpress.Object.Theme
description =
    Object.selectionForField "(Maybe String)" "description" [] (Decode.string |> Decode.nullable)


{-| -}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.Theme
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| Display name of the theme. This field is equivalent to WP\_Theme-&gt;get( &quot;Name&quot; ).
-}
name : SelectionSet (Maybe String) Wordpress.Object.Theme
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)


{-| The URL of the screenshot for the theme. The screenshot is intended to give an overview of what the theme looks like. This field is equivalent to WP\_Theme-&gt;get\_screenshot().
-}
screenshot : SelectionSet (Maybe String) Wordpress.Object.Theme
screenshot =
    Object.selectionForField "(Maybe String)" "screenshot" [] (Decode.string |> Decode.nullable)


{-| The theme slug is used to internally match themes. Theme slugs can have subdirectories like: my-theme/sub-theme. This field is equivalent to WP\_Theme-&gt;get\_stylesheet().
-}
slug : SelectionSet (Maybe String) Wordpress.Object.Theme
slug =
    Object.selectionForField "(Maybe String)" "slug" [] (Decode.string |> Decode.nullable)


{-| URI for the author/company website. This field is equivalent to WP\_Theme-&gt;get( &quot;Tags&quot; ).
-}
tags : SelectionSet (Maybe (List (Maybe String))) Wordpress.Object.Theme
tags =
    Object.selectionForField "(Maybe (List (Maybe String)))" "tags" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| A URI if the theme has a website associated with it. The Theme URI is handy for directing users to a theme site for support etc. This field is equivalent to WP\_Theme-&gt;get( &quot;ThemeURI&quot; ).
-}
themeUri : SelectionSet (Maybe String) Wordpress.Object.Theme
themeUri =
    Object.selectionForField "(Maybe String)" "themeUri" [] (Decode.string |> Decode.nullable)


{-| The current version of the theme. This field is equivalent to WP\_Theme-&gt;get( &quot;Version&quot; ).
-}
version : SelectionSet (Maybe Float) Wordpress.Object.Theme
version =
    Object.selectionForField "(Maybe Float)" "version" [] (Decode.float |> Decode.nullable)
