-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.UserRole exposing (capabilities, id, name)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| The capabilities that belong to this role
-}
capabilities : SelectionSet (Maybe (List (Maybe String))) Wordpress.Object.UserRole
capabilities =
    Object.selectionForField "(Maybe (List (Maybe String)))" "capabilities" [] (Decode.string |> Decode.nullable |> Decode.list |> Decode.nullable)


{-| The globally unique identifier for the role
-}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Object.UserRole
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)


{-| The UI friendly name of the role
-}
name : SelectionSet (Maybe String) Wordpress.Object.UserRole
name =
    Object.selectionForField "(Maybe String)" "name" [] (Decode.string |> Decode.nullable)
