-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Object.WritingSettings exposing (defaultCategory, defaultPostFormat, useSmilies)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


{-| Default post category.
-}
defaultCategory : SelectionSet (Maybe Int) Wordpress.Object.WritingSettings
defaultCategory =
    Object.selectionForField "(Maybe Int)" "defaultCategory" [] (Decode.int |> Decode.nullable)


{-| Default post format.
-}
defaultPostFormat : SelectionSet (Maybe String) Wordpress.Object.WritingSettings
defaultPostFormat =
    Object.selectionForField "(Maybe String)" "defaultPostFormat" [] (Decode.string |> Decode.nullable)


{-| Convert emoticons like :-) and :-P to graphics on display.
-}
useSmilies : SelectionSet (Maybe Bool) Wordpress.Object.WritingSettings
useSmilies =
    Object.selectionForField "(Maybe Bool)" "useSmilies" [] (Decode.bool |> Decode.nullable)
