-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Enum.PostTypeEnum exposing (PostTypeEnum(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| Allowed Post Types
-}
type PostTypeEnum
    = Attachment
    | Page
    | Post
    | Revision


list : List PostTypeEnum
list =
    [ Attachment, Page, Post, Revision ]


decoder : Decoder PostTypeEnum
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "ATTACHMENT" ->
                        Decode.succeed Attachment

                    "PAGE" ->
                        Decode.succeed Page

                    "POST" ->
                        Decode.succeed Post

                    "REVISION" ->
                        Decode.succeed Revision

                    _ ->
                        Decode.fail ("Invalid PostTypeEnum type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : PostTypeEnum -> String
toString enum =
    case enum of
        Attachment ->
            "ATTACHMENT"

        Page ->
            "PAGE"

        Post ->
            "POST"

        Revision ->
            "REVISION"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe PostTypeEnum
fromString enumString =
    case enumString of
        "ATTACHMENT" ->
            Just Attachment

        "PAGE" ->
            Just Page

        "POST" ->
            Just Post

        "REVISION" ->
            Just Revision

        _ ->
            Nothing
