-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.ScalarCodecs exposing (Id, codecs)

import Json.Decode as Decode exposing (Decoder)
import Wordpress.Scalar exposing (defaultCodecs)


type alias Id =
    Wordpress.Scalar.Id


codecs : Wordpress.Scalar.Codecs Id
codecs =
    Wordpress.Scalar.defineCodecs
        { codecId = defaultCodecs.codecId
        }
