-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Union exposing (CommentAuthorUnion(..), MenuItemObjectUnion(..), PostObjectUnion(..), TermObjectUnion(..))


type CommentAuthorUnion
    = CommentAuthorUnion


type MenuItemObjectUnion
    = MenuItemObjectUnion


type PostObjectUnion
    = PostObjectUnion


type TermObjectUnion
    = TermObjectUnion
