-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Wordpress.Interface.Node exposing (Fragments, fragments, id, maybeFragments)

import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (FragmentSelectionSet(..), SelectionSet(..))
import Json.Decode as Decode
import Wordpress.InputObject
import Wordpress.Interface
import Wordpress.Object
import Wordpress.Scalar
import Wordpress.ScalarCodecs
import Wordpress.Union


type alias Fragments decodesTo =
    { onCategory : SelectionSet decodesTo Wordpress.Object.Category
    , onTaxonomy : SelectionSet decodesTo Wordpress.Object.Taxonomy
    , onPostType : SelectionSet decodesTo Wordpress.Object.PostType
    , onPost : SelectionSet decodesTo Wordpress.Object.Post
    , onPage : SelectionSet decodesTo Wordpress.Object.Page
    , onUser : SelectionSet decodesTo Wordpress.Object.User
    , onComment : SelectionSet decodesTo Wordpress.Object.Comment
    , onCommentAuthor : SelectionSet decodesTo Wordpress.Object.CommentAuthor
    , onMediaItem : SelectionSet decodesTo Wordpress.Object.MediaItem
    , onTag : SelectionSet decodesTo Wordpress.Object.Tag
    , onRevision : SelectionSet decodesTo Wordpress.Object.Revision
    , onPlugin : SelectionSet decodesTo Wordpress.Object.Plugin
    , onTheme : SelectionSet decodesTo Wordpress.Object.Theme
    }


{-| Build an exhaustive selection of type-specific fragments.
-}
fragments :
    Fragments decodesTo
    -> SelectionSet decodesTo Wordpress.Interface.Node
fragments selections =
    Object.exhuastiveFragmentSelection
        [ Object.buildFragment "Category" selections.onCategory
        , Object.buildFragment "Taxonomy" selections.onTaxonomy
        , Object.buildFragment "PostType" selections.onPostType
        , Object.buildFragment "Post" selections.onPost
        , Object.buildFragment "Page" selections.onPage
        , Object.buildFragment "User" selections.onUser
        , Object.buildFragment "Comment" selections.onComment
        , Object.buildFragment "CommentAuthor" selections.onCommentAuthor
        , Object.buildFragment "MediaItem" selections.onMediaItem
        , Object.buildFragment "Tag" selections.onTag
        , Object.buildFragment "Revision" selections.onRevision
        , Object.buildFragment "Plugin" selections.onPlugin
        , Object.buildFragment "Theme" selections.onTheme
        ]


{-| Can be used to create a non-exhuastive set of fragments by using the record
update syntax to add `SelectionSet`s for the types you want to handle.
-}
maybeFragments : Fragments (Maybe decodesTo)
maybeFragments =
    { onCategory = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTaxonomy = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPostType = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPost = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPage = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onUser = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onComment = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onCommentAuthor = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onMediaItem = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTag = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onRevision = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onPlugin = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    , onTheme = Graphql.SelectionSet.empty |> Graphql.SelectionSet.map (\_ -> Nothing)
    }


{-| The id of the object
-}
id : SelectionSet Wordpress.ScalarCodecs.Id Wordpress.Interface.Node
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Wordpress.ScalarCodecs.codecs |> Wordpress.Scalar.unwrapCodecs |> .codecId |> .decoder)
